=== LisaRivalin/JSON-Schema-test/modelica-json-examples/schema-modelica.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "schema-modelica.json",
  "type": "array",
  "title": "JSON parsed Modelica file",
  "description": "Json representation of a Modelica model",
  "definitions": {
    "ModelicaBlock":{
      "description": "Info of a modelica block: model, parameter, input or output",
      "type": "array",
      "items": {
        "type":"object",
        "required": ["className", "name"],
        "properties": {
          "className":{
            "description": "Name of the class: no special characters or spaces",
            "type":"string",
            "pattern": "^([a-zA-Z0-9.*]*)$"
          },
          "name":{
            "description": "Name of the block: no special characters or spaces",
            "type":"string",
            "pattern": "^([a-zA-Z0-9.*]*)$"
          },
          "comment":{
            "description": "comment on the block: no special characters or spaces",
            "type":"string"
          },
          "value":{
            "description": "value of the block, if applicable",
            "type":"string"
          },
          "annotation":{
            "type" : "object",
            "required": ["dialog"],
            "properties":{
              "dialog":{
                "type": "object",
                "properties":{
                  "tab":{
                    "type":"string",
                    "examples": ["General"]
                  },
                  "group":{
                    "type":"string",
                    "examples": ["Parameters"]
                  }
                }
              }
            }
          },
          "modifications":{
            "type":"array",
            "items": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                },
                "isFinal":{
                  "type":"boolean"
                }
              }
            }
          }
        }
      }
    }
  },
  "items":{
    "type":"object",
    "required": [
      "modelicaFile",
      "topClassName"
    ],
    "properties": {
      "modelicaFile": {
        "decription": "Name of the Modelica file. Ends with '.mo'",
        "type": "string",
        "pattern": ".*.(mo|MO)"
      },
      "within": {
        "description": "Within statement from the Modelica file : no special characters or spaces",
        "type": "string",
        "pattern": "^([a-zA-Z0-9.*]*)$"
      },
      "topClassName": {
        "description": "Name of the top class of the Modelica model: no special characters or spaces ",
        "type": "string",
        "pattern": "^([a-zA-Z0-9.*]*)$"
      },
      "comment": {
        "description": "Comment on the model",
        "type" : "string"
      },
      "public": {
        "type":"object",
        "description" : "Public part of the modelica file",
        "properties" : {
          "parameters":{
            "$ref": "#/definitions/ModelicaBlock"
          },
          "models": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "inputs":{
            "$ref": "#/definitions/ModelicaBlock"
          },
          "outputs": {
            "$ref": "#/definitions/ModelicaBlock"
          }
        }
      },
      "protected": {
        "type":"object",
        "description": "Protected part of the modelica file",
        "properties": {
          "parameters":{
            "$ref": "#/definitions/ModelicaBlock"
          },
          "models":{
            "$ref": "#/definitions/ModelicaBlock"
          }
        }
      },
      "connections": {
        "type":"array",
        "items": {
          "type":"array",
          "items": {
          "type": "object",
          "required": ["instance"],
          "properties": {
            "instance": {
              "type": "string"
            },
            "connector":{
              "type":"string"
            }
          }
         }
        }
      },
      "info": {
        "description": "Informations of the model must be in html format",
        "type":"string",
        "pattern": "^(<(html|HTML)>)(.|\n)*(<\/(html|HTML)>)$"
      }
    }
  }
}

=== LisaRivalin/JSON-Schema-test/modelica-json-examples/package-simplified.json
[
  {
    "modelicaFile": "./package.mo",
    "topClassName": "FromModelica",
    "comment": "Package with test models",
    "public": {
      "models": [
        {
          "className": "Integer",
          "name": "one",
          "value": "1",
          "comment": "An integer constant with value 1"
        }
      ]
    }
  }
]

=== LisaRivalin/JSON-Schema-test/modelica-json-examples/BlockWithBlock1-simplified.json
[
  {
    "modelicaFile": "./BlockWithBlock1.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.BlockWithBlock1",
    "comment": "A block that instantiates another public and protected block",
    "public": {
      "models": [
        {
          "className": "Block1",
          "name": "bloPub",
          "comment": "A public block"
        }
      ]
    },
    "protected": {
      "models": [
        {
          "className": "Block1",
          "name": "bloPro",
          "comment": "A protected block"
        }
      ]
    }
  },
  {
    "modelicaFile": "Block1.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.Block1",
    "comment": "A block that instantiates nothing"
  }
]

=== LisaRivalin/JSON-Schema-test/modelica-json-examples/BlockInputOutput-simplified.json
[
  {
    "modelicaFile": "./BlockInputOutput.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.BlockInputOutput",
    "comment": "A block with an input and an output signal",
    "public": {
      "inputs": [
        {
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealInput",
          "name": "u",
          "comment": "Input connector"
        }
      ],
      "outputs": [
        {
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealOutput",
          "name": "y",
          "comment": "Output connector"
        }
      ]
    }
  }
]

=== LisaRivalin/JSON-Schema-test/modelica-json-examples/CustomPWithLimiter-simplified.json
[
  {
    "modelicaFile": "./CustomPWithLimiter.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.CustomPWithLimiter",
    "comment": "Custom implementation of a P controller with variable output limiter",
    "public": {
      "parameters": [
        {
          "className": "Real",
          "name": "k",
          "value": "2",
          "comment": "Constant gain",
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        }
      ],
      "models": [
        {
          "className": "Buildings.Controls.OBC.CDL.Continuous.Gain",
          "name": "gain",
          "comment": "Constant gain",
          "modifications": [
            {
              "name": "k",
              "value": "k",
              "isFinal": true
            }
          ]
        },
        {
          "className": "Buildings.Controls.OBC.CDL.Continuous.Min",
          "name": "minValue",
          "comment": "Outputs the minimum of its inputs"
        }
      ],
      "inputs": [
        {
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealInput",
          "name": "yMax",
          "comment": "Maximum value of output signal"
        },
        {
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealInput",
          "name": "e",
          "comment": "Control error"
        }
      ],
      "outputs": [
        {
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealOutput",
          "name": "y",
          "comment": "Control signal"
        }
      ]
    },
    "info": "<html>\n<p>\nBlock that outputs <code>y = min(yMax, k*e)</code>,\nwhere\n<code>yMax</code> and <code>e</code> are real-valued input signals and\n<code>k</code> is a parameter.\n</p>\n</html>",
    "connections": [
      [
        {
          "instance": "yMax"
        },
        {
          "instance": "minValue",
          "connector": "u1"
        }
      ],
      [
        {
          "instance": "e"
        },
        {
          "instance": "gain",
          "connector": "u"
        }
      ],
      [
        {
          "instance": "gain",
          "connector": "y"
        },
        {
          "instance": "minValue",
          "connector": "u2"
        }
      ],
      [
        {
          "instance": "minValue",
          "connector": "y"
        },
        {
          "instance": "y"
        }
      ]
    ]
  }
]
